# Generated by Django 5.0.3 on 2024-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HealthyBudget", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("type", models.CharField(default="expense", max_length=50)),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("type", models.CharField(default="income", max_length=50)),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
