# Generated by Django 5.0.3 on 2024-04-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyBudget', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
