# Generated by Django 5.0.3 on 2024-04-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyBudget', '0005_remove_profile_avatar_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
