# Generated by Django 5.0.4 on 2024-04-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyBudget', '0003_transaction_delete_expense_delete_income'),
        ('HealthyBudget', '0006_delete_profile'),
    ]

    operations = [
    ]
