# Generated by Django 5.0.4 on 2024-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyBudget', '0008_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
