# Generated by Django 5.0.4 on 2024-04-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_profile_options_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@me.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
